# Generated by Django 5.1.7 on 2025-05-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'customer'), ('business', 'business')], max_length=10)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(default='add information', max_length=64, null=True)),
                ('last_name', models.CharField(default='add information', max_length=64, null=True)),
                ('file', models.ImageField(default='add information', null=True, upload_to='uploads/')),
                ('location', models.CharField(default='add information', max_length=64, null=True)),
                ('tel', models.CharField(default='add information', max_length=64, null=True)),
                ('description', models.CharField(default='add information', max_length=256, null=True)),
                ('working_hours', models.CharField(default='add information', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
