# Generated by Django 5.1.7 on 2025-03-12 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_alter_userprofile_created_at_alter_userprofile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='coderr_app.offer'),
        ),
    ]
