# Generated by Django 5.1.7 on 2025-03-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_rename_user_offer_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='creator_id',
            new_name='user',
        ),
    ]
