# Generated by Django 5.1.7 on 2025-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0013_alter_userprofile_description_alter_userprofile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=255),
        ),
    ]
