# Generated by Django 5.1.7 on 2025-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0014_alter_offerdetails_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], editable=False, max_length=255),
        ),
    ]
