# Generated by Django 5.1.7 on 2025-04-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0016_alter_offerdetails_offer_type_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='coderr_app.offerdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=25),
        ),
    ]
