# Generated by Django 5.1.7 on 2025-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0017_order_offer_detail_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_detail',
        ),
    ]
