# Generated by Django 5.1.7 on 2025-04-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0018_remove_order_offer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='coderr_app.offerdetails'),
            preserve_default=False,
        ),
    ]
