# Generated by Django 5.1.7 on 2025-04-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0019_order_offer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.IntegerField(),
        ),
    ]
