# Generated by Django 5.1.7 on 2025-04-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0020_alter_order_offer_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_detail',
            new_name='offer_detail_id',
        ),
    ]
