# Generated by Django 5.1.7 on 2025-04-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0021_rename_offer_detail_order_offer_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coderr_app.offerdetails'),
        ),
    ]
