# Generated by Django 5.1.7 on 2025-04-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0023_rename_offer_detail_id_order_offer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='coderr_app.offerdetails'),
        ),
    ]
