# Generated by Django 5.1.7 on 2025-04-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0025_remove_order_offer_detail_alter_order_business_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=315, on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='coderr_app.offerdetails'),
            preserve_default=False,
        ),
    ]
