# Generated by Django 5.1.7 on 2025-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0027_alter_order_business_user_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.FloatField(),
        ),
    ]
