# Generated by Django 5.1.7 on 2025-04-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0028_alter_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='price',
            field=models.FloatField(),
        ),
    ]
