# Generated by Django 5.1.7 on 2025-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0029_alter_offerdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='user_details',
            field=models.JSONField(default={'first_name': 'exapmle', 'last_name': 'exapmle', 'username': 'exapmle'}),
            preserve_default=False,
        ),
    ]
