# Generated by Django 5.1.7 on 2025-05-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0030_offer_user_details'),
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetails',
            name='offer',
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='offer_app.offerdetails'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferDetails',
        ),
    ]
