# Generated by Django 5.1.7 on 2025-05-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0031_remove_offerdetails_offer_alter_order_offer_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
