# Generated by Django 5.1.7 on 2025-05-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0032_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
