# Generated by Django 5.1.7 on 2025-05-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0033_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
